on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - "**/*.kicad_pcb"

name: Render Previews
jobs:
  pngs:
    runs-on: ubuntu-latest
    name: "Export as PNGs"
    steps:
      # CHECKOUT
      - name: Checkout
        uses: actions/checkout@v2

      # PREVIEWS
      # 30 KEYS
      - name: Howarya
        uses: ./.github/actions/export-pngs
        with:
          pcb_file: ./pcbs/howarya/howarya.kicad_pcb
          pngs_dir: ./images/exports/
      - name: Swoop
        uses: ./.github/actions/export-pngs
        with:
          pcb_file: ./pcbs/swoop/swoop.kicad_pcb
          pngs_dir: ./images/exports/

      # UPDATE GALLERY
      # - name: Update gallery
      #   uses: stefanzweifel/git-auto-commit-action@v4.14.1
      #   with:
      #     commit_message: "Update gallery (automated)"
      #     commit_user_name: GitHub Actions Bot
      #     file_pattern: "**/*.png"
